### ISSUE TITLE
Right clicking in video opens context menu that can redirect out of presentation

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-video-folder#18]
* this applies to the production version of the widget *

Steps to reproduce:
1. Assign a presentation containing the video folder widget to a display.
2. Right click on the video.

Result:
A context menu listing "About JWPlayer..." appears.  Clicking on that will open a new website, replacing the presentation.

How it should work:
No menu should appear when right clicking on the video.

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=eb197d99-b568-4225-920e-82172f05216b?cid=e514fd51-fadd-4e19-94af-f92549772c7f

OS:
Ubuntu 14.04

Chrome Ver:
42.0.2311.152-1

**Comment by stulees** [comment]
@mfisher11 FYI closing this as it's been fixed and deployed.
