### ISSUE TITLE
Video playback does not begin until all files are downloaded

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-video-folder#19]
Steps to reproduce:
1.  Assign and schedule a presentation that has a video folder widget item pointing to a directory containing many videos.
2. Open the dev console and watch the network activity.

Result:
After a long delay (variable based on amount of videos and network speed) videos will play.
Assuming the content is not already cached, you can watch every file download before any video plays.  This delay can cause the client to (erroneously) believe the player has hung/crashed.

How it should work:
The delay before video playback begins should be as short as possible.

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=f7fbd9e4-1389-4657-97e6-b66a287dc875?cid=e514fd51-fadd-4e19-94af-f92549772c7f

OS:
Linux, Windows7, OSX, ChromeOS

Chrome Ver:
43.0.2357.124

**Comment by alanclayton** [comment]
@mfisher11 @stulees to clarify on how I think this should work, once any one of the videos in the folder has been downloaded, play that video, regardless of position. Once played, move on to the next, and if that one is not ready, keep moving through the list until you reach one that is ready and play it. 

What do you guys think? Also, @stulees does jw player have incorporate any sort of a loading icon to indicate to the User that the video is being downloaded vs just showing a black screen?

**Comment by mfisher11** [comment]
@alanclayton I could be completely mistaken (so, feel free to correct me @stulees ), but the files are downloaded, sequentially, in the order listed in the json file.  I don't think it would be possible to skip ahead per se.  In addition, I didn't see anything about a file size in that json file, either, so unless additional calls are made to obtain that information, prioritizing smaller files first would require additional calculation...

**Comment by stulees** [comment]
@alanclayton @mfisher11 The desired behaviour that Alan is suggesting won't work. The points Matthew mention are right and there is a further restriction on what API JWPlayer provides, particularly involving events to listen for. There is no "loaded" event that can be listened for with JWPlayer and on every individual video used in the playlist. There is only one `onReady(callback)` event to use which fires when the player has initialized and is ready for playback. 

What I'm not sure about is why apparently all videos are *requested and downloaded* before playback of the first video can occur. This seems odd, I have a hunch Rise Cache is involved in this delay happening in some way but it will require some debugging to understand what's happening. @mfisher11 Can you confirm that this issue/behaviour happens in preview as well as in CAP?

@alanclayton The player has a buffering icon that gets shown, but buffering is not the same as browser downloading the file.

**Comment by mfisher11** [comment]
@stulees In preview, videos will start almost immediately.  They don't wait until all of the downloads have completed.

**Comment by stulees** [comment]
@mfisher11 Thanks. @alanclayton FYI, this only happens in CAP when Rise Cache is running.

**Comment by stulees** [comment]
@mfisher11 FYI closing this as its been fixed and deployed.
