### ISSUE TITLE
*BETA VERSION* Videos can't/won't start if autoplay is unchecked, then show video controls is unchecked

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-video-folder#9]
Steps to reproduce:
1. Create a presentation with containing the new video folder widget and configured with content:
    http://s3.amazonaws.com/widget-video-folder-rv-test/0.1.0/dist/widget.html
    http://s3.amazonaws.com/widget-video-folder-rv-test/0.1.0/dist/settings.html
2. In the configuration screen, uncheck autoplay.
3. Uncheck show video controls.
4. Save everything and show presentation (this happens on a display as well as preview)

Result:
Video never starts playing, and since controls are hidden, it cannot be started.
(if autoplay is left checked before unchecking show controls--it plays as expected)

How it should work:
This is a bit subjective, but since checking "show video controls" hides the autoplay toggle, shouldn't it automatically enable autostart as opposed to using whatever the state was at the time?

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=f7c827f7-e536-4d29-b8b8-7ba67ec5a8e9?cid=e514fd51-fadd-4e19-94af-f92549772c7f

OS:
This occurs in preview (Xubuntu 14.04) and CAP on Ubuntu 14.04.

Chrome Ver:
Version 42.0.2311.135 (64-bit)

**Comment by stulees** [comment]
@mfisher11 Latest Beta version includes a fix to this bug. Please verify and close, thanks. @alanclayton FYI

**Comment by mfisher11** [comment]
@stulees This issue has been resolved.  Thanks!
@alanclayton FYI
